# Usa una imagen oficial de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el package.json y package-lock.json (desde ./servidor)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de tu código (server.js, conexion.js, etc.)
COPY . .

# Expone el puerto en el que correrá tu app (definido en el .env)
EXPOSE ${APP_PORT}

# El comando para iniciar tu servidor (basado en tu estructura)
CMD [ "node", "server.js" ]